### PR TITLE
Replace outdated dependency with security flags

### PR DESCRIPTION
**Pull request by shcheklein**
`pytest-celery` raises security scan alert (e.g. https://github.com/iterative/dvc-task/actions/runs/8883067284/job/24389104408?pr=128)

It depends on `retry` libm which itself depends (for no good reason) on `py` which is flagged for security and is outdated:

https://github.com/invl/retry/issues/58
https://github.com/invl/retry/pull/60

It seems it's not maintained (last release / update is ~8 years ago).

A replacement is `funcy` - lightweight (no dependencies AFAIK), license is good, maintained. We have been using it in DVC.org for a while.

### CODE REVIEW

**Comment by shcheklein** [comment]
hey @Nusnus, thanks for running the pipeline for this 🙏 . Let me know if you need anything here or is it good to go as is.

**Comment by Nusnus** [comment]
> hey @Nusnus, thanks for running the pipeline for this 🙏 . Let me know if you need anything here or is it good to go as is.

Thanks for the PR!
I have a very busy week and many PRs to review, but I will sure get to everything as soon as I can.

I’ll let you know if anything else is needed, thank you!

**Comment by jerr0328** [comment]
Was noticing the same issue and found this PR. If for some reason funcy doesn't work there's also tenacity as an option, though I guess this mostly just needs to be updated again so that tests pass?

**Comment by Nusnus** [comment]
> Was noticing the same issue and found this PR. If for some reason funcy doesn't work there's also tenacity as an option, though I guess this mostly just needs to be updated again so that tests pass?

I'm leaning towards tenacity as well.
Over my head with Celery stuff at the moment so it takes longer, but I didn't forget this issue ♥️

**Comment by Nusnus** [comment]
@shcheklein @jerr0328 @skshetry
Issue fixed, including all of the following as well:

CleanShot 2024-07-17 at 01 47 28@2x

**Comment by Nusnus** [comment]
> @shcheklein @jerr0328 @skshetry
> Issue [fixed](https://github.com/celery/pytest-celery/pull/342), including all of the following as well:
> 
> CleanShot 2024-07-17 at 01 47 28@2x
> 

Released in https://github.com/celery/pytest-celery/releases/tag/v1.0.1

**Pull request closed without merging**
