### PR TITLE
Upgrade to codecov/codecov-action@v4

### PR DESCRIPTION
**Pull request by cclauss**
Like #180 but following the directions at
* https://github.com/codecov/codecov-action?tab=readme-ov-file#usage

`token: ${{ secrets.CODECOV_TOKEN }} # required`

### CODE REVIEW

**Review by Nusnus — APPROVED** [review]
Thank you!!
🚀🚀🚀

Much appreciated 😊

**Comment by Nusnus** [comment]
It appears to fail on `main`: https://github.com/celery/pytest-celery/actions/runs/7773551496

Can you please give it a look @cclauss ?

**Comment by cclauss** [comment]
That is why I made this pull request a `DRAFT` and not ready for review.

A repo maintainer needs to go to https://app.codecov.io/github/celery/pytest-celery/settings to get the token as discussed at https://docs.codecov.com/docs/frequently-asked-questions

Then the token will need to be added to the repo as a secret as discussed at https://docs.codecov.com/docs/adding-the-codecov-token#github-actions

**Comment by Nusnus** [comment]
> That is why I made this pull request a `DRAFT` and not ready for review.
> 
> A repo maintainer needs to go to https://app.codecov.io/github/celery/pytest-celery/settings to get the token as discussed at https://docs.codecov.com/docs/frequently-asked-questions
> 
> Then the token will need to be added to the repo as a GitHub Secret as discussed at https://docs.codecov.com/docs/adding-the-codecov-token#github-actions

Sorry to jump the gun - many ppl forget to change the draft to ready or just set to ready regardless of actual readiness.

Added the token and now everything works, thank you!

**Pull request merged**
